name: "Lint"
on:
  workflow_call:
    inputs:
      ruby-version:
        description: Ruby version
        type: string
        required: false
        default: "3.3.4"
      node-version:
        description: Node version
        type: string
        required: false
        default: "20.15.1"

jobs:
  ruby_linting:
    name: "Lint ruby"
    env:
      GOVUK_NOTIFY_API_KEY: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.193.0
        with:
          ruby-version: ${{ inputs.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Lint Ruby
        run: bundle exec rubocop

  js_linting:
    name: "Lint JS"
    env:
      GOVUK_NOTIFY_API_KEY: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Set up Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Lint install
        run: npm i -g standard

      - name: Lint JS
        run: |-
          npm run lint:js

  scss_linting:
    name: "Lint SCSS"
    env:
      GOVUK_NOTIFY_API_KEY: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Set up Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Style lint install
        run: npm i -g stylelint stylelint-config-gds

      - name: Lint SCSS
        run: |-
          npm run lint:scss

  erb_linting:
    name: "Lint ERB"
    env:
      GOVUK_NOTIFY_API_KEY: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.193.0
        with:
          ruby-version: ${{ inputs.ruby-version }}

      - name: Install dependencies
        run: bundle install

      - name: Lint ERB Templates
        if: false
        run: |-
          bundle exec erblint --lint-all

  terraform_linting:
    name: Lint Terraform
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout Code

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Check formatting
        run: terraform fmt -check -recursive -diff
        working-directory: config/terraform

      - name: Download vendor modules
        run: make ci staging bin/terrafile

      - name: Validate
        run: |
          terraform init -backend=false
          terraform validate -no-color
